### PR TITLE
Add field selection and gene filtering

### PR DESCRIPTION
**Pull request by awm33**
### Motivation

We would like to filter for samples with mutations on certain genes. We would also like to limit how much data is returned by selecting fields to return.

Closes https://github.com/cognoma/core-service/issues/33

### API changes

Adds `fields` to each GET list/retrieve endpoint.

### Implementation Notes

Added `fields` selection across the board, since it seems useful.

Had to move the MutationSerializer and add its Meta class later in order to do a circular reference.

### Functional Tests

Hitting /genes and /samples with mutations queries and field selection.

### CODE REVIEW

**Comment by awm33** [comment]
@dhimmel I remember talking with you briefly about mutations.status last meeting. Does it still make sense to remove the `status` field and only have an entry for gene-sample pairs that are mutated? @stephenshank This may impact your work on loading the gene/sample data.

@bdolly Does this make sense for the frontend use case?

You can filter by mutations__gene which expects the gene PK id or mutations__gene__entrezid to filter by entrezid. You can add it multiple times to filter for multiple entries, ex `mutations__gene=1234&mutations__gene=2356&mutations__gene=21883`

I don't really like having an `id` PK field on genes and entrezid as a separate field. All joins have to be on `id` since that's the PK on the model. But this is importing the genes model from a another project.

**Comment by bdolly** [comment]
@awm33 would `/mutations__gene=1234` be the params that are passed to the elastic search request from the frontend?

**Comment by awm33** [comment]
@bdolly Not sure what you mean. This isn't elasticsearch, elasticsearch may be used to to full text searching of genes. This would tell you for a given gene or genes, what samples have mutations for those genes.

**Comment by bdolly** [comment]
@awm33 sorry I got confused. 

So on the front-end this would be baked into a Gene or Disease Type data model and used to calculate the "positives" and "negatives" for a sample set/disease type given user selected genes?

**Comment by awm33** [comment]
@bdolly Yes, you could take the resulting samples and do something like

```js
geneIds = [1234,2356,21883]
...
GET /samples?mutations__gene=1234&mutations__gene=2356&mutations__gene=21883
...
// create an object to accumulate gene positive counts
geneCounts = geneIds.reduce(function (acc, geneId) { acc[geneId] = 0; }, {});
// count the number of positives for each gene.
geneCounts = samples.reduce(function (counts, sample) { return sample.mutations.reduce(function(counts, mutation) { counts[mutation.gene]++; }, counts); }, geneCounts);
```

The result from above is an object, keyed by gene id, with counts for each "positive" or mutation. The number of "negatives" would be total number of samples minus that number.

To quickly get the total number of samples, do `GET /samples?limit=1` and get the `count` from the outer object

`GET /samples?limit=1`
```json
{
	"count": 12678,
	"next": "...",
	"previous": "...",
	"results": [
		{
			"sample_id": "TCGA-02-0047-01",
			"disease": "GBM",
			"mutations": [
				1
			],
			"gender": "Male",
			"age_diagnosed": 78
		}
	]
}
```

**Pull request merged**
