### PR TITLE
Updated settings to allow HTML browsable API

### PR DESCRIPTION
**Pull request by abeedvisram**
### Motivation

Use Django REST Framework default HTML / web browsable API in response to issue #41 

### API changes

None

### Implementation Notes

- Split up the definition of the Django apps so as to clarify where the apps are coming from
- Use of `django.contrib.staticfiles` requires setting the `STATIC_URL` which, for now, has been set to a rather unimaginative value of `/static/`

### Functional Tests

Tests passing locally:

```
./manage.py test -v2 -k
Using existing test database for alias 'default' ('test_cognoma_core_service')...
Operations to perform:
  Synchronize unmigrated apps: organisms, rest_framework, postgres, genes, staticfiles
  Apply all migrations: api, contenttypes
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
Running migrations:
  No migrations to apply.
test_cannot_update_other_user_classifier (api.test.test_classifiers.ClassifierTests) ... ok
test_create_classifier (api.test.test_classifiers.ClassifierTests) ... ok
test_create_from_internal_service (api.test.test_classifiers.ClassifierTests) ... ok
test_expansion (api.test.test_classifiers.ClassifierTests) ... ok
test_get_classifier (api.test.test_classifiers.ClassifierTests) ... ok
test_list_classifiers (api.test.test_classifiers.ClassifierTests) ... ok
test_must_be_logged_in (api.test.test_classifiers.ClassifierTests) ... ok
test_update_classifier (api.test.test_classifiers.ClassifierTests) ... ok
test_update_from_internal_service (api.test.test_classifiers.ClassifierTests) ... ok
test_get_disease (api.test.test_diseases.DiseaseTests) ... ok
test_list_diseases (api.test.test_diseases.DiseaseTests) ... ok
test_entrezid_filter (api.test.test_genes.GeneTests) ... ok
test_get_gene (api.test.test_genes.GeneTests) ... ok
test_list_genes (api.test.test_genes.GeneTests) ... ok
test_get_mutations (api.test.test_mutations.MutationTests) ... ok
test_list_mutations (api.test.test_mutations.MutationTests) ... ok
test_get_sample (api.test.test_sample.SampleTests) ... ok
test_list_samples (api.test.test_sample.SampleTests) ... ok
test_cannot_update_other_user (api.test.test_users.UserTests) ... ok
test_create_user (api.test.test_users.UserTests) ... ok
test_get_user (api.test.test_users.UserTests) ... ok
test_get_user_self (api.test.test_users.UserTests) ... ok
test_list_users (api.test.test_users.UserTests) ... ok
test_update_user (api.test.test_users.UserTests) ... ok
test_user_update_must_be_logged_in (api.test.test_users.UserTests) ... ok

----------------------------------------------------------------------
Ran 25 tests in 0.413s

OK
Preserving test database for alias 'default' ('test_cognoma_core_service')...
```

### Screenshots/Logs

samples

### CODE REVIEW

**Comment by awm33** [comment]
@abeedvisram This looks great!

The only concerning thing for me would be things like user.random_slugs which is only placed in the response at certain times, or if this can handle the `?expand=...` parameter.

@dhimmel Do you think we should go ahead with the rendering the browsable API or just plain JSON in the browser? I think you're main concern with https://github.com/cognoma/core-service/issues/41 was being able to render it in the browser for demo purposes?

**Comment by dhimmel** [comment]
> Do you think we should go ahead with the rendering the browsable API or just plain JSON in the browser?

Most APIs I use will return the JSON payload in the browser (often with newlines/indents). I think this is really helpful for users -- a single URL should return the same payload no matter what requests it.

Regarding a "browsable API", that could be useful, but can it live on a different URL than the API call?

@awm33 not saying anything about whether these features are in scope for this PR... just my general opinion.

**Comment by awm33** [comment]
> Most APIs I use will return the JSON payload in the browser (often with newlines/indents).

@dhimmel Yes, they are probably not inspecting the Accept header to determine what type of thing is calling it (ie browser vs API client)

@abeedvisram It might better to just force JSON for any value of Accept. A step further may be [custom content type](http://www.django-rest-framework.org/api-guide/content-negotiation/) negotiation to add indentation for web browsers.

**Comment by dcgoss** [comment]
Fairly certain the Accept header is inspected. The API client should receive JSON and the browser should receive the "browsable" version off the same URL. We can keep them separate if we wanted, of course.

**Comment by abeedvisram** [comment]
Just so that we're clear, this is the behaviour with the above PR. Please let me know if there is anything that looks amiss.

### Browser

#### Default
browsable

#### Force to JSON via querystring
html_force_json


### API Client

### Default

```
$ curl -X GET http://localhost:8000/genes > /tmp/curl_output.txt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 66416    0 66416    0     0   426k      0 --:--:-- --:--:-- --:--:--  426k
$ cat /tmp/curl_output.txt| pp_json| head -n 20
{
    "count": 60139,
    "next": "http://localhost:8000/genes?limit=100&offset=100",
    "previous": null,
    "results": [
        {
            "entrez_gene_id": 1,
            "symbol": "A1BG",
            "description": "alpha-1-B glycoprotein",
            "chromosome": "19",
            "gene_type": "protein-coding",
            "synonyms": [
                "A1B",
                "ABG",
                "GAB",
                "HYST2477"
            ],
            "aliases": [
                "alpha-1B-glycoprotein",
                "HEL-S-163pA",
 ...
```

#### Force to HTML via Accept header

```
$ curl -v -H "Accept: text/javascript, text/html, application/xml, */*" http://localhost:8000/genes > /tmp/curl_html.txt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying ::1...
* connect to ::1 port 8000 failed: Connection refused
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8000 (#0)
> GET /genes HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.49.0
> Accept: text/javascript, text/html, application/xml, */*
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Date: Mon, 23 Jan 2017 22:15:49 GMT
< Server: WSGIServer/0.2 CPython/3.4.3
< Allow: GET, HEAD, OPTIONS
< Content-Type: text/html; charset=utf-8
< Vary: Accept
< 
{ [16384 bytes data]
100  200k    0  200k    0     0   810k      0 --:--:-- --:--:-- --:--:--  813k
* Closing connection 0
$ head /tmp/curl_html.txt -n 20    




<!DOCTYPE html>
<html>
  <head>
    

      
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta name="robots" content="NONE,NOARCHIVE" />
      

      <title>Gene List – Django REST framework</title>

      
        
          <link rel="stylesheet" type="text/css" href="/static/rest_framework/css/bootstrap.min.css"/>
          <link rel="stylesheet" type="text/css" href="/static/rest_framework/css/bootstrap-tweaks.css"/>

...
```

**Comment by dhimmel** [comment]
That looks good to me... especially if the Django Rest Framework GUI provides useful functionality. I also like how you can override with `?format=json`

**Comment by awm33** [comment]
The querystring option looks nice, then it can be forced for demos / reference.

@abeedvisram  Awesome work!

**Comment by dhimmel** [comment]
@awm33, this doesn't currently look to be deployed to http://api.cognoma.org/. What's the deployment process?

**Pull request merged**
