### PR TITLE
Email tweak, user/classifier security enhancements, /genes/ pagination

### PR DESCRIPTION
**Pull request by dcgoss**
- /users/ only provides access to create users. Endpoint will not
return a list of users anymore. (resolves https://github.com/cognoma/core-service/issues/77)
- access to /users/id/ is only given to users accessing themselves and
internal services. Users/anonymous users cannot access other users.
- /classifiers/ only provides access to create classifiers. Endpoint
will not return a list of classifiers anymore.
- Before, accessing the /genes/ endpoint really slowed down the server
because it had to process 100 genes and their mutations. I lowered the
pagination size to 10 which speeds things up significantly. (resolves https://github.com/cognoma/core-service/issues/81)
- Notebook upload request would fail if the user had no email registered. Added
fail_silently=True to bypass this failure. (resolves https://github.com/cognoma/core-service/issues/80)
- Updated the email message to include a link to the nbviewer website (per suggestion from @dhimmel)
- Simplified MLWorkers permission logic

### CODE REVIEW

**Comment by dcgoss** [comment]
@bdolly is this ok for the frontend?

**Comment by dcgoss** [comment]
@dhimmel do these access permissions sound good?

**Comment by bdolly** [comment]
@dcgoss what was the `/genes` endpoint being used for? Currently in the front-end the genes are pulled from and external [myGeneInfo](http://mygene.info/) endpoint

**Comment by dcgoss** [comment]
@bdolly if the frontend isn't using it then we're not using it either. When a Classifier is created it gets connected to the Gene objects that it references, but we don't use the /genes/ url in core-service or ml-workers.

**Comment by bdolly** [comment]
@dcgoss I think that endpoint was originally created in-case we wanted to use genes from the Cognoma DB instead of from a third-party so probably good to deprecate it for now.

@dhimmel would you agree?

**Comment by dcgoss** [comment]
@bdolly I'm going to go ahead and remove the /genes/ endpoint for now. Am I also safe in removing the /mutations/ endpoint?

**Comment by dcgoss** [comment]
Went ahead and removed in https://github.com/cognoma/core-service/pull/79/commits/5baada33c2aa4e6759b5b6725c826418fd807ff3

**Pull request merged**
