### PR TITLE
Internal Auth

### PR DESCRIPTION
**Pull request by awm33**
### Motivation

Internal services/processes inside of cognoma need to be able to mutate classifier and user objects. For example core service needs to interact with the task service, and workers need to interact with both.

Closes https://github.com/cognoma/core-service/issues/31

### API changes

A new authentication method has been added.

### Implementation Notes

Json Web Tokens allow us to maintain internal tokens without having a central table of tokens. Services just need to check against a public key. The private key is kept secret and not in production.

### Functional Tests

Hitting various endpoints including POSTing/PUTing users, also added integration tests.

### CODE REVIEW

**Comment by dhimmel** [comment]
> The private key is kept secret and not in production.

Got it... the private key here is just an example for development.

Let's give @stephenshank, @cgreene, or @dcgoss (or anyone else) until Wednesday to review this.  If no one reviews, then @awm33 you should proceed and merge.

**Comment by dcgoss** [comment]
Hey guys! I know I've been absent/silent recently, school etc. has been distracting. I have been trying to keep up to date, and it looks like thanks to @awm33 you've/we've made some great progress. I'll take a look at this PR since I have experience with JWT, but I'm sure it will be fine.

**Comment by dcgoss** [comment]
Yeah, almost everything looks good with the implementation. I haven't written an implementation from scratch before (I have used https://github.com/GetBlimp/django-rest-framework-jwt), but this seems like it makes sense. 

I do have a question. Where does the user receive their JWT? It seems like in the tests it is generated, and there appears to be a generator for internal services, but I can't find where the user gets their JWT. In my other Django project there is an endpoint where you supply your auth info (username and password) and the API replies with a JWT that you supply with future API requests, but since we don't have traditional accounts it seems we need an alternate method.

**Comment by dcgoss** [comment]
One other thing. Is there a reason that the JWT secret key is separate from the Django secret key? I have no clue if that is standard practice or not, but it seems that if it doesn't matter you could potentially just use the Django secret key.

**Comment by awm33** [comment]
@dcgoss JWTs are used for internal auth only and are manually generated using the command in the PR. Each running service would have one. Users use the URL token, which are [generated on user creation](https://github.com/cognoma/core-service/blob/master/api/serializers.py#L19).

The URL user token is part of the angular app routes and is passed to the API through the Authorization header as a Bearer token. This also allows people to use the API from other clients, like their own scripts. It's not the most secure solution for a web app, a cookie would be better, but we're also not protecting secrets, just preventing some misuse.

The reason that I don't want to use the django secret is that I want to use a private/public key pair. The private key is never stored on a server and the public key can be used to verify the token. The public key itself could even known to the public. Only someone/something with the private key can generate a valid token.

Side note, I'm using JWTs for service authentication, which is acceptable, but it should not be used for web application authentication. [Stop using JWT for sessions](http://cryto.net/~joepie91/blog/2016/06/13/stop-using-jwt-for-sessions/) [Does JWT put your web app at risk?](http://blog.prevoty.com/does-jwt-put-your-web-app-at-risk).

**Comment by awm33** [comment]
One thing that could be added here is some sort of scoping. This gives god like access, but the ml code probably never needs to update a user object. That may be overkill.

**Comment by dcgoss** [comment]
@awm33 Ok, got it - LGTM.

It seems like JWTs have issues for web apps, but on mobile apps they do alright since you have a better way to persistently store authentication data.

**Comment by awm33** [comment]
> but on mobile apps they do alright

@dcgoss Absolutely, even desktop clients too, anywhere the runtime environment is trusted. [Browsers are getting closer](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) but their not their yet.

**Comment by bdolly** [comment]
@awm33 @dcgoss @cgreene @stephenshank  
Given that JWT are only used internally and the Users `random_slug` are used for client-side auth is there an endpoint to retrieve an existing user and their classifiers from the DB given their `random_slug` ? 

Currently it seems the only way to retrieve the `random_slug` is to POST to `/users` which generates a new user and returns the full object which can then be stored in a cookie/sessionStorage etc. This works well for auto-generating users and not needing an account login.

However there needs to be a way to retrieve a full user object and their associated classifiers from the DB given their `random_slug` passed from the url. This would allow for a "login" where you can append the users `random_slug` to the url (`cognoma.org/query-results/<random_slug>`) and use that value to then view their user profile and classifier results. This approach is critical to allowing users to share their classifier results with others and bookmark their unique account url to "login" on other machines where their user cookie has not been previously stored.

**Pull request merged**
