### PR TITLE
Implemented user retrieval by random_slug

### PR DESCRIPTION
**Pull request by dcgoss**
Resolves issue https://github.com/cognoma/core-service/issues/58.
Inspired by PR https://github.com/cognoma/core-service/pull/65.

Note: while this was outside the scope of this commit, I did notice
that on the /users/ endpoint a list of all users is returned with no
authentication required. On the /classifiers/ endpoint a list of all
classifiers is returned with no authentication required. This seems
like a security concern.

### CODE REVIEW

**Comment by dcgoss** [comment]
@bdolly just wanted to verify with you that this addresses your original issue.

**Comment by dcgoss** [comment]
For example:
screen shot 2017-06-27 at 5 11 00 pm
`classifier_set` gives the primary keys (ids) of classifiers tied to the user. How this field is rendered can be changed pretty easily; you can nest the serializer of the classifier in the user serializer, you can give a bunch of hyperlinks to each individual classifier, etc.

**Comment by bdolly** [comment]
As far as I can tell without pulling it down and testing it should work. 

For the classifier_set we can leave the pks for now and add more data to it as we implement more User functionality. 

The main concern for the front-end on his was handling user login to add a random_slug into the POST request to create a classifier and then be able to retrieve those results

**Comment by bdolly** [comment]
Another idea I had for this was Tom required a preflight request to grab a JWT first to add to the GET headers. That way at least we know the GET request is originating from our front-end and not just Simone popping the URL in a browser or REST tester

**Comment by dcgoss** [comment]
The issue I see with the JWT is that I would assume you need some sort of auth in order to get the JWT from the server. If we are going with the random_slug for auth, then to me getting a JWT would defeat the purpose of the random_slug. Currently, if you send a POST to the /classifiers/ endpoint it 401s with `Authentication credentials were not provided.` If you then attach the value `Bearer <slug>` to the `Authorization` key in your request the classifier is created.

**Comment by bdolly** [comment]
I was thinking the JWT would be used for the GET `/users/<slug>` endpoint that returns the single user object. That way your first form of auth is the possession of the `random_slug` value and the second form is that the GET `/users/<slug>` - Header `Authorization: JWT  <jwt_token>`. 

So the flow would be to first send a POST to grab the JWT from the server, this way we know the request is coming from our system. Then send the GET `/users/<slug>` with the JWT in the header. 

screen shot 2017-06-28 at 10 24 35 am

**Comment by dcgoss** [comment]
Is there any auth required in the request to obtain the JWT from the server? If not it doesn't seem to provide any more verification than just the slug, it just adds an extra step into the process.

**Comment by dcgoss** [comment]
Going to go ahead and merge because it seems like the core issue was resolved. We can always revisit.

**Pull request merged**
