### PR TITLE
Prod changes config

### PR DESCRIPTION
**Pull request by awm33**
### Motivation

We'd like Cognoma to work in prod :)

### Functional Tests

`curl http://api.cognoma.org/samples`

### CODE REVIEW

**Comment by dcgoss** [comment]
Is the AWS ELB actually created or is that a placeholder?

**Comment by awm33** [comment]
@dhimmel That curl request should work.

@dcgoss That ELB exists, it's an internal ELB pointing to the core service. A publicly accessible ELB points to nginx.

I still need to add SSL to that ELB. We could also use SSL across the board, but all of the service-to-service traffic is inside a VPC.

**Comment by dhimmel** [comment]
Looks like SSL is now active (and required) :+1:. 

Confirming that `curl https://api.cognoma.org/samples` returns 

```json
{"count":0,"next":null,"previous":null,"results":[]}
```

However, going to that URL in the browser returns `Server Error (500)`. Do we not want to give the JSON payload to web browser as well? What causes this discrepancy in behavior?

**Comment by awm33** [comment]
@dhimmel You are entering that into the browser location bar which will send a request with the Accept header as:

```
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
````

The 500 is an error, it should return `415 Unsupported Media Type` or force application/json by default.

Looks like [the parser needs to be explicitly setup](http://www.django-rest-framework.org/api-guide/parsers/)

**Comment by dhimmel** [comment]
> The 500 is an error, it should return `415 Unsupported Media Type` or force application/json by default.

My vote would be to have these API calls return JSON even to the web browser. It adds lot's of convenience to be able to see the JSON payload that URL returns in the browser. Maybe it could also be smart enough to add newlines when queried by a browser.

**Pull request merged**
